# Generated by Django 5.2.3 on 2025-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZMR_MOBILTY_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='inquiry_type',
            field=models.CharField(choices=[('franchise', 'Franchise Opportunity'), ('vehicle', 'Vehicle Purchase'), ('service', 'Service Support'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
