# Generated by Django 5.2.3 on 2025-10-27 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZMR_MOBILTY_APP', '0002_alter_contactmessage_inquiry_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('inquiry_type', models.CharField(choices=[('franchise', 'Franchise Opportunity'), ('vehicle', 'Vehicle Purchase'), ('service', 'Service Support'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FranchiseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('preferred_city', models.CharField(choices=[('noida', 'Noida'), ('lucknow', 'Lucknow'), ('dehradun', 'Dehradun'), ('jaipur', 'Jaipur'), ('chandigarh', 'Chandigarh')], max_length=20)),
                ('business_experience', models.TextField()),
                ('investment_capacity', models.DecimalField(decimal_places=2, help_text='Investment capacity in INR', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for admin')),
            ],
            options={
                'verbose_name': 'Franchise Application',
                'verbose_name_plural': 'Franchise Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('rental_type', models.CharField(choices=[('daily', 'Daily Rental'), ('monthly', 'Monthly Rental')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('active', 'Active Rental'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rental Booking',
                'verbose_name_plural': 'Rental Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('charging_stations', models.IntegerField(default=0)),
                ('battery_swapping_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('google_maps_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Service Location',
                'verbose_name_plural': 'Service Locations',
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('e2w', 'Electric 2-Wheeler'), ('e3w', 'Electric 3-Wheeler'), ('e4w', 'Electric 4-Wheeler')], max_length=10)),
                ('description', models.TextField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('battery_range', models.IntegerField(help_text='Range in kilometers')),
                ('max_speed', models.IntegerField(help_text='Maximum speed in km/h')),
                ('charging_time', models.CharField(help_text="e.g., '4-6 hours'", max_length=50)),
                ('features', models.TextField(help_text='Key features, one per line')),
                ('image', models.ImageField(blank=True, upload_to='vehicles/')),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
                'ordering': ['vehicle_type', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='pickup_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZMR_MOBILTY_APP.servicelocation'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZMR_MOBILTY_APP.vehiclemodel'),
        ),
    ]
